# Generated by Django 5.0.6 on 2024-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emergency',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
    ]
