# Generated by Django 5.0.6 on 2024-06-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_remove_veterinarian_pet_alter_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mine',
            field=models.BooleanField(default=True, verbose_name='Is mine?'),
        ),
    ]
