# Generated by Django 5.0.6 on 2024-06-29 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_contact_mine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='veterinarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='care.veterinarian', verbose_name='Vet'),
        ),
    ]
