# Generated by Django 5.0.6 on 2024-06-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tutor_address_alter_contact_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetUUID',
            new_name='TagUUID',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='pet_uuid',
            new_name='tag',
        ),
    ]
