# Generated by Django 5.0.6 on 2024-06-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_taguuid_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagUUID',
            new_name='Tag',
        ),
    ]
