# Generated by Django 5.0.6 on 2024-06-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_remove_veterinarian_pet_alter_contact_address_and_more'),
        ('core', '0006_tag_exported_tag_url_alter_allotment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care.veterinarian', verbose_name='Vet'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='allotment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allotment', verbose_name='Allotment'),
        ),
    ]
