# Generated by Django 5.0.6 on 2024-06-29 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_alter_contact_veterinarian'),
        ('core', '0007_pet_veterinarian_alter_tag_allotment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'managed': True, 'ordering': ('joined_date',), 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='petname',
            options={'managed': True, 'verbose_name': 'Petname', 'verbose_name_plural': 'Petnames'},
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='apelido',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='pet',
            name='medical_condition',
            field=models.TextField(blank=True, null=True, verbose_name='Medical Condition'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='care.veterinarian', verbose_name='Vet'),
        ),
    ]
