# Generated by Django 5.0.6 on 2024-07-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pet_options_alter_petname_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
    ]
